Replace 'ѕ' with 's' in test docstrings
Since the recent switch to python3, I've been noticing that some of the tests
have been aborting with the following error when I use LANG=en_US instead of
LANG=en_US.UTF-8:

UnicodeEncodeError: 'latin-1' codec can't encode character '\u0455' in position 57: ordinal not in range(256)

Arguably, I should run with a unicode locale while running the test, but it
*looks* to me like the original ѕ was not intended.